---
# In order for this to work, you have to set the Docker Hub username and
# password:
#
# travis env set DOCKER_USERNAME myusername
# travis env set DOCKER_PASSWORD secretsecret
language: shell

script:
  - docker build . -t esanumeventapp/ruby-mysql
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push esanumeventapp/ruby-mysql:latest

notifications:
  email: false
  slack:
    rooms:
      secure: "RtCMXwdJfE64e6fExM4HOFTu4KeGzn9TX3608q926kNi551Z/b0xFAxUhNNwptTG/xZjPPPRmku7KlVJTGgMfqW6Y3FgIKehYIoJCPFX5M5Gft4bA+D29ug9snCLWX+OBXeFyrdNoGhugwnSYhGvCvvfgsL++ABEoJENwrPL9Eo="
  on_success: change
  on_failure: always
  notify: true
