---
# In order for this to work, you have to set the Docker Hub username and
# password:
#
# travis env set DOCKER_USERNAME myusername
# travis env set DOCKER_PASSWORD secretsecret
language: shell

script:
  - docker build . -t esanumeventapp/ruby-mysql
  - docker push esanumeventapp/ruby-mysql:latest
